const jsonGames = [
 
  {
    name: "THE WTICHER 3: WILD HUNT",
    description: "Eres Geralt de Rivia, cazador de monstruos. En un continente devastado por la guerra e infestado de criaturas, tu misión es encontrar a Ciri, la niña de la profecía, un arma viviente que puede alterar el mundo tal y como lo conocemos.",
    released: "2015-05-18",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg?t=1675178392",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["CD PROJEKT RED"],
    genre: ["Rol"],
    price: 40,
    discount: 0,
  },

  {
    name: "TOMB RAIDER",
    description: "Tomb Raider relata la historia del origen de Lara Croft y su transformación de una joven chica a una endurecida superviviente.",
    released: "2013-03-05",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/203160/header.jpg",
    calification: "5",
    MinRequirements:
    "Minimum:\nOS:Windows XP / Windows Vista / Windows 7\nProcessor:1.8 GHz Processor\nMemory:512 MB RAM\nGraphics:3D graphics card compatible with DirectX 9\nDirectX®:9.0\nHard Drive:2 GB HD space",
    RecommendRequirements: "",
    company: ["Crystal Dynamics"],
    genre: ["Action", "Adventure"],
    price: 15,
    discount: 0,
  },

  {
    name: "LEFT 4 DEAD 2",
    description: "Ambientado en el apocalipsis zombi, Left 4 Dead 2 (L4D2) es la esperadísima secuela del galardonado Left 4 Dead, el juego cooperativo número 1 de 2008. Este FPS cooperativo de acción y terror os llevará a ti y a tus amigos por las ciudades, pantanos y cementerios del Sur Profundo",
    released: "2009-11-17",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/550/header.jpg",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Valve"],
    genre: ["Action"],
    price: 10,
    discount: 0,
  },

  {
    name: "LIMBO",
    description: "Dudoso sobre el destino de su hermana, un niño entra en LIMBO",
    released: "2011-08-02",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/48000/header.jpg",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Playdead"],
    genre: ["Action", "Adventure", "Indie"],
    price: 1,
    discount: 90,
  },

  {
    name: "AMONG US",
    description: "Un juego de socialización local o en línea de trabajo en equipo y traición para 4 a 15 jugadores... ¡ambientado en el espacio!",
    released: "2018-11-16",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/945360/header.jpg?t=1673370035",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Innersloth"],
    genre: ["Casual"],
    price: 5,
    discount: 0,
  },

  {
    name: "TERRARIA",
    description: "¡Cava, lucha, explora, construye! Con este juego de aventuras repleto de acción nada es imposible. ¡Pack de Cuatro también disponible!",
    released: "2011-05-16",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg?t=1666290860",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Re-Logic"],
    genre: ["Action", "Adventure", "Indie", "Rol"],
    price: 10,
    discount: 0,
  },

  {
    name: "RUST",
    description: "El único objetivo en Rust es sobrevivir. Todo quiere que mueras: la vida silvestre de la isla y otros habitantes, el medio ambiente, otros sobrevivientes. Haz lo que sea necesario para durar otra noche.",
    released: "2018-02-08",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg?t=1671160999",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Facepunch Studios"],
    genre: ["Action", "Adventure", "Indie", "Rol"],
    price: 40,
    discount: 0,
  },

  {
    name: "JUMP KING",
    description: "¡Acepta el desafío y enfréntate a unas plataformas de alto riesgo en Jump King! Lucha durante el ascenso en busca de la legendaria buenorra, pero ten cuidado; errar un salto puede convertirse en una larga caída de vuelta...",
    released: "2019-05-03",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1061090/header.jpg?t=1669716164",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Nexile"],
    genre: ["Action", "Adventure", "Indie"],
    price: 13,
    discount: 0,
  },
 
  {
    name: "PHASMOPHOBIA",
    description: "Phasmophobia es un horror psicológico cooperativo en línea para 4 jugadores. La actividad paranormal va en aumento y depende de usted y su equipo usar todo el equipo de caza de fantasmas a su disposición para recopilar la mayor cantidad de evidencia posible.",
    released: "2020-09-18",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/739630/capsule_616x353.jpg?t=1674232976",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Kinetic Games"],
    genre: ["Action", "Indie", "Early Access"],
    price: 14,
    discount: 0,
  },

  {
    name: "WATCH DOGS®: LEGION",
    description: "En Watch Dogs: Legion, tu misión es crear una resistencia para salvar a Londres de la debacle en un futuro próximo.",
    released: "2023-01-26",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/2239550/capsule_616x353.jpg?t=1674755684",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Ubisoft Toronto"],
    genre: ["Action", "Adventure"],
    price: 60,
    discount: 0,
  },

  {
    name: "FORSPOKEN",
    description: "Forspoken narra la historia de Frey, una joven neoyorquina que acaba en el hermoso y cruel mundo de Athia. Mientras averigua cómo volver a casa, tendrá que usar sus nuevas dotes mágicas para recorrer paisajes enormes y enfrentarse a seres monstruosos.",
    released: "2023-01-24",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1680880/capsule_616x353.jpg?t=1678382734",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Luminous Productions"],
    genre: ["Action", "Adventure", "Rol"],
    price: 70,
    discount: 0,
  },

  {
    name: "DEAD SPACE",
    description: "Vuelve el clásico de terror y supervivencia de ciencia ficción, recreado completamente para ofrecer una experiencia más inmersiva (incluidas mejoras visuales, sonoras y de jugabilidad) al mismo tiempo que se mantiene fiel a la emocionante visión del juego original.",
    released: "2023-01-27",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1693980/capsule_616x353.jpg?t=1678446810",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Motive"],
    genre: ["Action", "Adventure"],
    price: 60,
    discount: 0,
  },

  {
    name: "PIZZA TOWER",
    description: "Pizza Tower es un juego de plataformas en 2D de ritmo rápido inspirado en la serie Wario Land, con énfasis en el movimiento, la exploración y el ataque de puntuación. Con pixel art muy estilizado inspirado en los dibujos animados de los años 90 y una banda sonora muy enérgica.",
    released: "2023-01-26",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/2231450/capsule_616x353.jpg?t=1674756021",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Tour De Pizza"],
    genre: ["Action", "Indie"],
    price: 20,
    discount: 0,
  },

  {
    name: "AQUATICO",
    description: "Aquatico es un juego de supervivencia de construcción de ciudades ambientado en las profundidades marinas. Construye estratégicamente una ciudad sumergida sobre el lecho marino y enfrenta los retos que conlleva una vida oceánica..",
    released: "2023-01-12",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1675900/capsule_616x353.jpg?t=1677772500",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Digital Reef Games."],
    genre: ["Simulation", "Strategy"],
    price: 25,
    discount: 0,
  },

  {
    name: "SEA OF THIEVES",
    description: "Sea of Thieves ofrece la experiencia de piratasdefinitiva, desde la navegación y elcombate hasta la exploración y elsaqueo: todo para disfrutar de la vidapirata y convertirteenleyenda. No hay funcionesestablecidas, tienes total libertad para enfrentarte al mundo",
    released: "2020-06-03",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1172620/capsule_616x353.jpg?t=1673489975",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Rare Ltd"],
    genre: ["Action", "Adventure"],
    price: 25,
    discount: 0,
  },

  {
    name: "VALHEIM",
    description: "Un brutal juego de supervivencia y exploración multijugador, ambientado en un purgatorio generado de forma procedural e inspirado en la cultura vikinga. ¡Lucha, construye y conquista tu viaje en una saga digna de la bendición de Odin!",
    released: "2021-02-02",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/capsule_616x353.jpg?t=1676365340",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Iron Gate AB"],
    genre: ["Action", "Adventure", "Indie", "Rol", "Early Access"],
    price: 20,
    discount: 0,
  },

  {
    name: "STARDEW VALLEY",
    description: "Un brutal juego de supervivencia y exploración multijugador, ambientado en un purgatorio generado de forma procedural e inspirado en la cultura vikinga. ¡Lucha, construye y conquista tu viaje en una saga digna de la bendición de Odin!",
    released: "2016-02-26",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg?t=1666917466",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["ConcernedApe"],
    genre: ["Indie", "Rol", "Simulation"],
    price: 15,
    discount: 0,
  },

  {
    name: "PROJECT ZOMBOID",
    description: "Project Zomboid es lo último en supervivencia zombie. Solo o en MP: saqueas, construyes, fabricas, luchas, cultivas y pescas en una lucha por sobrevivir. Un conjunto de habilidades de juego de rol extremo, un vasto mapa, una zona de pruebas enormemente personalizable y un simpático mapache tutorial esperan a los desprevenidos. Entonces, ¿cómo vas a morir?",
    released: "2013-11-08",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg?t=1667832656",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["The Indie Stone"],
    genre: ["Indie", "Rol", "Simulation", "Early Access"],
    price: 20,
    discount: 0,
  },

  {
    name: "AMONG US",
    description: "Un juego de socialización local o en línea de trabajo en equipo y traición para 4 a 15 jugadores... ¡ambientado en el espacio!",
    released: "2018-11-16",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/945360/header.jpg?t=1673370035",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Innersloth"],
    genre: ["Casual"],
    price: 5,
    discount: 0,
  },

  {
    name: "OCTOPATH TRAVELER II",
    description: "Un juego nuevo de rol de la saga OCTOPATH TRAVELER, cuya primera entrega se publicó en 2018 y vendió más de tres millones de copias en todo el mundo.",
    released: "2023-02-24",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1971650/capsule_616x353.jpg?t=1678490077",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Square Enix", "ACQUIRE Corp"],
    genre: ["Rol"],
    price: 60,
    discount: 0,
  },

  {
    name: "WO LONG: FALLEN DYNASTY",
    description: "Nuevo RPG de acción de fantasía oscura en los Tres Reinos, de Team NINJA, creadores de Nioh",
    released: "2023-03-03",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1448440/capsule_616x353.jpg?t=1677836173",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["KOEI TECMO GAMES CO., LTD."],
    genre: ["Action", "Adventure", "Rol"],
    price: 60,
    discount: 0,
  },

  {
    name: "LIKE A DRAGON: ISHIN!",
    description: "En 1860 Kioto está plagado de desigualdades y un samurái cambiará el curso de la historia en su búsqueda de la justicia. Desenvaina tu espada y únete a la revolución en esta aventura histórica. Reserva ahora para añadir tres armas exclusivas a tu arsenal.",
    released: "2023-03-03",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1805480/capsule_616x353.jpg?t=1678469799",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Ryu Ga Gotoku Studio"],
    genre: ["Action", "Adventure"],
    price: 60,
    discount: 0,
  },

  {
    name: "HI-FI RUSH",
    description: "Siente el ritmo mientras el aspirante a estrella Chai y su variopinto equipo luchan con una megacorporación en atronadores combates de ritmo. De la mano de Tango Gameworks, llega Hi-Fi RUSH, un juego de acción en el que el mundo se sincroniza con la música.",
    released: "2023-01-25",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1817230/header.jpg?t=1675874328",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Tango Gameworks"],
    genre: ["Action"],
    price: 30,
    discount: 0,
  },

  {
    name: "ATOMIC HEART",
    description: "Ten encuentros explosivos en un delirante y sublime mundo utópico. Adapta tu estilo de combate a cada rival, aprovecha el entorno y mejora el equipamiento para cumplir la misión. El precio de averiguar la verdad tendrás que pagarlo con sangre.",
    released: "2023-02-20",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/668580/header.jpg?t=1676995676",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Mundfish"],
    genre: ["Action", "Adventure", "Rol"],
    price: 60,
    discount: 0,
  },

  {
    name: "OCTOPATH TRAVELER II",
    description: "Un juego nuevo de rol de la saga OCTOPATH TRAVELER, cuya primera entrega se publicó en 2018 y vendió más de tres millones de copias en todo el mundo.",
    released: "2023-02-24",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1971650/capsule_616x353.jpg?t=1678490077",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Square Enix", "ACQUIRE Corp"],
    genre: ["Rol"],
    price: 60,
    discount: 0,
  },

  {
    name: "HOGWARTS LEGACY",
    description: "Hogwarts Legacy es un RPG inmersivo de acción en mundo abierto. Ahora puedes tomar el control de la acción y ser el centro de tu propia aventura en el mundo mágico.",
    released: "2023-02-10",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/990080/capsule_616x353.jpg?t=1676412613",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Avalanche Software"],
    genre: ["Action", "Adventure", "Rol"],
    price: 60,
    discount: 0,
  },

  {
    name: "SONS OF THE FOREST",
    description: "Enviado a buscar a un multimillonario desaparecido en una isla remota, te encuentras en un infierno infestado de caníbales. Crea, construye y lucha para sobrevivir, solo o con amigos, en este nuevo y aterrador simulador de horror y supervivencia de mundo abierto.",
    released: "2023-02-23",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1326470/capsule_616x353.jpg?t=16771796397",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Endnight Games Ltd"],
    genre: ["Rol"],
    price: 30,
    discount: 0,
  },

  {
    name: "ASSASINS CREED VALHALLA",
    description: "Ponte en la piel de Eivor, una leyenda vikinga en busca de gloria. Saquea a tus enemigos, haz prosperar tu asentamiento y consolida tu poder político.",
    released: "2022-12-06",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/2208920/capsule_616x353.jpg?t=1671135934",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Ubisoft Montreal"],
    genre: ["Action", "Adventure", "Rol"],
    price: 60,
    discount: 0,
  },



  {
    name: "COMPANY OF HEROES 3",
    description: "Más grande y mejor que nunca, Company of Heroes 3 combina un combate emocionante con opciones estratégicas más profundas en un impresionante escenario de guerra en el Mediterráneo. En Company of Heroes 3, cada batalla cuenta una historia... ¿cuál es la tuya?",
    released: "2023-02-23",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1677280/capsule_616x353.jpg?t=1677780045",
    calification: "3",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Relic Entertainment"],
    genre: ["Action", "Strategy"],
    price: 60,
    discount: 0,
  },

  {
    name: "FAR CRY 5",
    description: "Bienvenido a Hope County, Montana, la tierra de los valientes y de la libertad, pero también de la secta apocalíptica conocido camo 'Puerta del Edén'. Enfréntate a Joseph Seed, líder de la secta, y sus hermanos para liberar a la comunidad de Hope.",
    released: "2018-03-27",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/552520/capsule_616x353.jpg?t=1671031724",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Ubisoft Toronto"],
    genre: ["Action", "Adventure"],
    price: 60,
    discount: 0,
  },

  {
    name: "RED DEAD REDEMPTION II",
    description: "Con más de 175 premios al Juego del año y más de 250 valoraciones perfectas, Red Dead Redemption 2 es la épica historia de Arthur Morgan y la banda de Van der Linde, que huyen por toda América en el albor de una nueva era.",
    released: "2019-12-05",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg?t=1671485009",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Rockstar Games"],
    genre: ["Action", "Adventure"],
    price: 60,
    discount: 67,
  },

  {
    name: "FIFA 23",
    description: "FIFA 23 nos acerca a The World's Game con la tecnología HyperMotion2, la FIFA World Cup™ masculina y femenina disponibles durante la temporada, clubes femeninos, función de juego cruzado* y mucho más.",
    released: "2022-09-30",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/1811260/capsule_616x353.jpg?t=1677074188",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["EA Canada & EA Romania"],
    genre: ["Simulation", "Sports"],
    price: 70,
    discount: 0,
  },

  {
    name: "SUN HAVEN",
    description: "Construye tu granja y relaciones con la gente del pueblo, o avanza en una búsqueda de magia, monstruos y dragones. ¡Sube de nivel a través de un árbol de habilidades en el modo multijugador de 8 personas o en una aventura en solitario!",
    released: "2023-03-10",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/945360/header.jpg?t=1673370035",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Pixel Sprout Studios"],
    genre: ["Adventure", "Casual", "Indie", "Rol", "Simulation"],
    price: 25,
    discount: 20,
  },

  {
    name: "DARK SOULS 3",
    description: "Dark Souls continúa redefiniendo los límites con el nuevo y ambicioso capítulo de esta serie revolucionaria, tan aclamada por la crítica. ¡Prepárate para sumergirte en la oscuridad!",
    released: "2016-04-11",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/374320/capsule_616x353.jpg?t=1671097812",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["FromSoftware, Inc."],
    genre: ["Action"],
    price: 60,
    discount: 0,
  },

  {
    name: "KENSHI",
    description: "Un videojuego de rol de mundo abierto con estrategias a tiempo real y con eventos que no tienen una secuencia argumentativa lineal. Sé un comerciante, un ladrón, un rebelde, un señor de la guerra, un aventurero, un granjero, un esclavo o tan sólo comida para los caníbales.",
    released: "2018-12-06",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/233860/capsule_616x353.jpg?t=1652436681",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Lo-Fi Games"],
    genre: ["Action", "Indie", "Rol", "Simulation", "Strategy"],
    price: 60,
    discount: 0,
  },


  {
    name: "FALLOUT 4",
    description: "Bethesda Game Studios, el galardonado creador de Fallout 3 y The Elder Scrolls V: Skyrim, os da la bienvenida al mundo de Fallout 4, su juego más ambicioso hasta la fecha y la siguiente generación de mundos abiertos.",
    released: "2015-11-10",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/377160/capsule_616x353.jpg?t=1650909928",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Bethesda Game Studios"],
    genre: ["Rol"],
    price: 20,
    discount: 0,
  },

  {
    name: "FOOTBALL MANAGER 2023",
    description: "Confecciona la plantilla de tus sueños, supera a tus rivales y vive la emoción de las grandes noches europeas en la UEFA Champions League. Emprende tu viaje hacia la gloria.",
    released: "2022-11-07",
    img: "https://cdn.cloudflare.steamstatic.com/steam/apps/377160/capsule_616x353.jpg?t=1650909928",
    calification: "4",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Sports Interactive"],
    genre: ["Simulation", "Sports"],
    price: 60,
    discount: 0,
  },

  {
    name: "GAME DEV TYCOON",
    description: "En Game Dev Tycoon, reproduces la historia de la industria de los juegos al iniciar tu propia empresa de desarrollo de videojuegos en los años 80. Crea los juegos más vendidos. Investiga nuevas tecnologías e inventa nuevos tipos de juegos. Conviértase en el líder del mercado y gane seguidores en todo el mundo.",
    released: "2013-08-29",
    img: "https://cdn.akamai.steamstatic.com/steam/apps/239820/capsule_616x353.jpg?t=1667167358",
    calification: "5",
    MinRequirements: "",
    RecommendRequirements: "",
    company: ["Greenheart Games"],
    genre: ["Casual", "Indie", "Simulation", "Strategy"],
    price: 10,
    discount: 0,
  },






];
module.exports = { jsonGames };
